### ISSUE TITLE
Browserpass not found when using brew on M1 (not via rosetta)

### ISSUE THREAD

**Issue by avxkim** [Amar1729/homebrew-formulae#9] opened 2021-04-26 13:16 UTC
Is browserpass from your repository compatible with apple m1?

**Comment by dnapier** [comment] 2021-04-26 13:52
Yes, I can verify it's working for me.

**Comment by Amar1729** [comment] 2021-04-26 17:26
@webcoderkz did you try installing before filing this issue? This tap doesn't provide a bottle for m1 architecture but you should be able to build it just fine.

**Comment by joshtch** [comment] 2021-04-26 21:59
This is not working on M1 for me, either. The Rosetta build works as expected, but building with Apple Silicon seems to be broken. 

Steps to reproduce:

1. Have Apple Silicon machine (obviously).
2. [Set up Homebrew for M1 following the instructions here.](https://soffes.blog/homebrew-on-apple-silicon) Namely:

       $ sudo mkdir -p /opt/homebrew
       $ sudo chown -R $(whoami):staff /opt/homebrew
       $ curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C /opt/homebrew

3. Run `arch --arm64 /opt/homebrew/bin/brew install amar1729/formulae/browserpass`.

The result of the last command as I post this:

```sh
==> Installing browserpass from amar1729/formulae
==> Downloading https://github.com/browserpass/browserpass-native/files/3062744/request.hex.txt
Already downloaded: /Users/josh/Library/Caches/Homebrew/downloads/af54f5b32e20c9746065a4c2fbbf8cf0db5dc35ccd787f3f37477da16378c531--request.hex.txt
==> Downloading https://github.com/browserpass/browserpass-native/releases/download//browserpass-darwin64-.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "browserpass"
Download failed: https://github.com/browserpass/browserpass-native/releases/download//browserpass-darwin64-.tar.gz
```

Used `/opt/homebrew/bin/brew edit browserpass` to swap lines 4 & 5 of the formula:

```diff
@@ -1,8 +1,8 @@
 class Browserpass < Formula
   desc "Host application for browser extension providing access to your password store"
   homepage "https://github.com/browserpass/browserpass-native"
-  url "https://github.com/browserpass/browserpass-native/releases/download/#{version}/browserpass-darwin64-#{version}.tar.gz"
   version "3.0.7"
+  url "https://github.com/browserpass/browserpass-native/releases/download/#{version}/browserpass-darwin64-#{version}.tar.gz"
   sha256 "97b9a9068a3c88fb1d52d42a1712e199da5865a4c6f8352b9fe3eae1ee86c746"
 
   bottle do
```

Run it again:

```
$ arch --arm64 /opt/homebrew/bin/brew install amar1729/formulae/browserpass
==> Installing browserpass from amar1729/formulae
==> Downloading https://github.com/browserpass/browserpass-native/files/3062744/request.hex.txt
Already downloaded: /Users/josh/Library/Caches/Homebrew/downloads/af54f5b32e20c9746065a4c2fbbf8cf0db5dc35ccd787f3f37477da16378c531--request.hex.txt
==> Downloading https://github.com/browserpass/browserpass-native/releases/download/3.0.7/browserpass-darwin64-3.0.7.tar.gz
Already downloaded: /Users/josh/Library/Caches/Homebrew/downloads/f68f93545fa69db7e0d8c2eca6e6b8150b18768574ebc182f7d38070cf47b2c6--browserpass-darwin64-3.0.7.tar.gz
==> make configure
==> make install
==> Caveats
********************************************************************************
* To configure your browser, RUN THE FOLLOWING:

$ PREFIX='/usr/local/opt/browserpass' make hosts-BROWSER-user -f /usr/local/opt/browserpass/lib/browserpass/Makefile

* Where BROWSER is one of the following: [chromium chrome vivaldi brave firefox]
********************************************************************************
==> Summary
🍺  /opt/homebrew/Cellar/browserpass/3.0.7: 11 files, 4.1MB, built in 2 seconds
```

It seems to have worked? Then run the relevant `make` command:

```sh
$ PREFIX='/usr/local/opt/browserpass' make hosts-firefox-user -f /usr/local/opt/browserpass/lib/browserpass/Makefile
make: /usr/local/opt/browserpass/lib/browserpass/Makefile: No such file or directory
make: *** No rule to make target '/usr/local/opt/browserpass/lib/browserpass/Makefile'.  Stop.
```

Whoops! The prefix is wrong. Edit the formula:

```diff
@@ -39,7 +39,7 @@ class Browserpass < Formula
       ********************************************************************************
       * To configure your browser, RUN THE FOLLOWING:
 
-      $ PREFIX='/usr/local/opt/browserpass' make hosts-BROWSER-user -f /usr/local/opt/browserpass/lib/browserpass/Makefile
+      $ PREFIX='#{prefix}' make hosts-BROWSER-user -f '#{prefix}/lib/browserpass/Makefile'
 
       * Where BROWSER is one of the following: [chromium chrome vivaldi brave firefox]
       ********************************************************************************
```

Run corrected `make` command:

```sh
$ PREFIX='/opt/homebrew/opt/browserpass' make hosts-firefox-user -f '/opt/homebrew/opt/browserpass/lib/browserpass/Makefile'
'/Users/josh/Library/Application Support/Mozilla/NativeMessagingHosts/com.github.browserpass.native.json' -> '/opt/homebrew/opt/browserpass/lib/browserpass/hosts/firefox/com.github.browserpass.native.json'
```

Success? Not so fast...

In Firefox, the extension seems to be communicating with the binary, at least. 

<img width="360" alt="Browser add-on working popup" src="https://user-images.githubusercontent.com/4016526/116152251-aacf4800-a6b3-11eb-9421-f5bb5498d8b6.png">

Select a login, though, and this happens:

<img width="823" alt="Error: Unable to fetch and parse login fields: Unable to detect the location of the gpg binary to use Unable to detect the location of the gpg binary" src="https://user-images.githubusercontent.com/4016526/116152432-e833d580-a6b3-11eb-9b49-3b45be13acb4.png">

The error in plaintext:

`Error: Unable to fetch and parse login fields: Error: {"status":"error","code":22,"version":3000007,"params":{"action":"fetch","error":"Unable to detect the location of the gpg binary to use","message":"Unable to detect the location of the gpg binary"}}`

Not sure where to go from here.

**Comment by joshtch** [comment] 2021-04-26 22:57
(@Amar1729 I submitted a pull request for just the mentioned changes, if you want them.)

**Comment by Amar1729** [comment] 2021-04-27 01:03
That's an odd gpg error. It looks like browserpass supports configuring the path to gpg, so that might be a decent workaround for the issue if we can't get it fixed on m1. From the readme:

> If Browserpass is unable to locate the proper `gpg` binary, try configuring a full path to your `gpg` in the browser extension settings or in `.browserpass.json` file in the root of your password store:
> 
> ```json
> {
>     "gpgPath": "/full/path/to/gpg"
> }
> ```

**Comment by joshtch** [comment] 2021-04-27 03:13
Thanks, that did it! 

(Edit for posterity: I set `/opt/homebrew/bin/gpg` as the gpg binary.)

**Comment by avxkim** [comment] 2021-04-27 03:15
@Amar1729 can you accept @joshtch PR? i just tried again: `brew install browserpass` and got the same error:

```
##O=#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "browserpass"
Download failed: https://github.com/browserpass/browserpass-native/releases/download//browserpass-darwin64-.tar.gz
```

**Comment by Amar1729** [comment] 2021-04-27 17:01
We had to update the PR, but it's just been merged. @webcoderkz try now.

**Comment by avxkim** [comment] 2021-04-27 17:03
@Amar1729 i did as @joshtch `brew edit browserpass`, i wonder, i've edited my local cached brew bottle? Does it affect somehow if i make `brew install browserpass` again? Do i need to revert my `brew edit browserpass` edits previously made?

**Comment by Amar1729** [comment] 2021-04-27 17:15
`brew edit` won't change the local bottle (bottle is the binary package, whereas formula is the ruby file defining this software).

It would probably be best to:
1. go to the location of the tap (you can run `brew edit browserpass` again and exit without changes, and brew will tell you the filepath)
2. run `git stash` to stash your changes
3. run `brew update` to pull new changes
4. try `brew reinstall browserpass`

**Comment by avxkim** [comment] 2021-04-27 17:34
Just did as you wrote, seems like it works. Can i drop the stashed changes now?

**Comment by Amar1729** [comment] 2021-04-27 17:40
Yup.

Thanks to @joshtch again for fixing this up!

**Closed as completed by Amar1729** 2021-04-27 17:40 UTC

**Comment by max-baz** [comment] 2022-02-08 15:44
Hello, FYI there is now a pre-built binary available for M1, in case you can make use of it in the tap:

https://github.com/browserpass/browserpass-native/releases/download/3.0.8/browserpass-darwin64-3.0.8.tar.gz
https://github.com/browserpass/browserpass-native/releases/download/3.0.8/browserpass-darwin-arm64-3.0.8.tar.gz

**Comment by Amar1729** [comment] 2022-02-10 19:54
@maximbaz very cool, thanks! I'll see if I can bump to that in a new release soon.
